#!/bin/bash

usage() {
	echo "Usage: $0 <file>"
	echo "  <file>  File containing positive integers (one per line)"
}

if [ -z "$1" ] || [ ! -f "$1" ]; then
	usage
	exit 1
fi

filename="$1"
while IFS= read -r num; do
	res=$(factor "$num")
	snum=$(echo $res | tr ":" "=" | cut -d " " -f 2 | tr -d " ")
	tnum=$(expr $num / $snum)
	echo "$num=$tnum*$snum"
done < "$filename"
